- name: 'Check if certificate already exists: "{{ domains }}"'
  ansible.builtin.stat:
    path: '/etc/letsencrypt/live/{{ domains | split(",") | first | replace("*.", "") }}/cert.pem'
  register: certificate

- name: 'Issue certificate: "{{ domains }}"'
  ansible.builtin.command:
    cmd: >-
      certbot certonly
      --manual-auth-hook {{ happy_eyeballs.base_path }}/cert-scripts/auth-hook-handler.sh
      --manual-cleanup-hook {{ happy_eyeballs.base_path }}/cert-scripts/auth-cleanup-handler.sh
      --email {{ certbot.email }}
      --manual
      --preferred-challenges=dns
      --agree-tos
      -d {{ domains }}
  changed_when: true
  when: not certificate.stat.exists
