- name: Copy webtester site source directory
  ansible.posix.synchronize:
    src: 'site-src/'
    dest: '{{ happy_eyeballs.base_path }}/www-root/'
    owner: false
    group: false
    rsync_opts:
      - '--exclude=.DS_Store'
      - '--chown={{ happy_eyeballs.user.name }}:{{ happy_eyeballs.user.name }}'

- name: Copy webtester static files
  ansible.builtin.template:
    src: 'static/{{ item }}.j2'
    dest: '{{ happy_eyeballs.base_path }}/www-root/{{ item }}'
    owner: '{{ happy_eyeballs.user.name }}'
    group: '{{ happy_eyeballs.user.name }}'
    mode: '0644'
  with_items:
    - 'delays.csv'
    - 'he-test-domain'
