- name: Add IPv4 addresses to webserver interface
  ansible.builtin.shell:
    cmd: 'ip a add {{ item }}/{{ happy_eyeballs.webserver.ipv4_net_mask }} dev {{ happy_eyeballs.webserver.interface }}'
  register: result
  failed_when: 'result.rc != 0 and "File exists" not in result.stderr'
  with_items:
    - '{{ happy_eyeballs.webserver.delays | map(attribute="ipv4") | list }}'
    - '{{ happy_eyeballs.webserver.ipv4 }}'
    - '{{ happy_eyeballs.webserver.http3.ipv4 }}'
    - '{{ happy_eyeballs.webserver.he_v3_quic.ipv4 }}'

- name: Add IPv6 addresses to webserver interface
  ansible.builtin.shell:
    cmd: 'ip a add {{ item }}/{{ happy_eyeballs.webserver.ipv6_net_mask }} dev {{ happy_eyeballs.webserver.interface }}'
  register: result
  failed_when: 'result.rc != 0 and "File exists" not in result.stderr'
  with_items:
    - '{{ happy_eyeballs.webserver.delays | map(attribute="ipv6") | list }}'
    - '{{ happy_eyeballs.webserver.ipv6 }}'
    - '{{ happy_eyeballs.webserver.http3.ipv6 }}'
    - '{{ happy_eyeballs.webserver.he_v3_quic.ipv6 }}'

- name: Add IPv4 addresses to nameserver interface
  ansible.builtin.shell:
    cmd: 'ip a add {{ item }}/{{ happy_eyeballs.nameserver.ipv4_net_mask }} dev {{ happy_eyeballs.nameserver.interface }}'
  register: result
  failed_when: 'result.rc != 0 and "File exists" not in result.stderr'
  with_items:
    - '{{ happy_eyeballs.nameserver.ipv4 }}'

- name: Add IPv6 addresses to nameserver interface
  ansible.builtin.shell:
    cmd: 'ip a add {{ item }}/{{ happy_eyeballs.nameserver.ipv6_net_mask }} dev {{ happy_eyeballs.nameserver.interface }}'
  register: result
  failed_when: 'result.rc != 0 and "File exists" not in result.stderr'
  with_items:
    - '{{ happy_eyeballs.nameserver.ipv6 }}'

- name: Add IPv4 address to webtester interface
  ansible.builtin.shell:
    cmd: 'ip a add {{ happy_eyeballs.webtester.ipv4 }}/{{ happy_eyeballs.webtester.ipv4_net_mask }} dev {{ happy_eyeballs.webtester.interface }}'
  register: result
  failed_when: 'result.rc != 0 and "File exists" not in result.stderr'

- name: Add IPv6 address to webtester interface
  ansible.builtin.shell:
    cmd: 'ip a add {{ happy_eyeballs.webtester.ipv6 }}/{{ happy_eyeballs.webtester.ipv6_net_mask }} dev {{ happy_eyeballs.webtester.interface }}'
  register: result
  failed_when: 'result.rc != 0 and "File exists" not in result.stderr'


# ip route add default via 138.246.253.254 dev eno4.220 metric 512
# ip -6 route add default via fe80::21c:73ff:fe00:99 dev eno4.220 metric 512
