- name: Create caddy directory
  ansible.builtin.file:
    path: '{{ happy_eyeballs.base_path }}/caddy'
    owner: '{{ happy_eyeballs.user.name }}'
    group: '{{ happy_eyeballs.user.name }}'
    mode: '0755'
    state: 'directory'

- name: Create caddy data directory
  ansible.builtin.file:
    path: '{{ happy_eyeballs.base_path }}/caddy/data'
    owner: '{{ happy_eyeballs.user.name }}'
    group: '{{ happy_eyeballs.user.name }}'
    mode: '0755'
    state: 'directory'

- name: Copy caddy dockerfile
  ansible.builtin.template:
    src: 'Dockerfile.j2'
    dest: '{{ happy_eyeballs.base_path }}/caddy/Dockerfile'
    owner: root
    group: root
    mode: '0644'
  notify: restart he-caddy

- name: Copy caddy docker compose file
  ansible.builtin.template:
    src: 'docker-compose.yml.j2'
    dest: '{{ happy_eyeballs.base_path }}/caddy/docker-compose.yml'
    owner: root
    group: root
    mode: '0644'
  notify: restart he-caddy

- name: Copy Caddyfile
  ansible.builtin.template:
    src: 'Caddyfile.j2'
    dest: '{{ happy_eyeballs.base_path }}/caddy/Caddyfile'
    owner: '{{ happy_eyeballs.user.name }}'
    group: '{{ happy_eyeballs.user.name }}'
    mode: '0644'
  notify: restart he-caddy

- name: Copy custom caddy module src
  ansible.posix.synchronize:
    src: 'custom-caddy-module/'
    dest: '{{ happy_eyeballs.base_path }}/caddy/custom-caddy-module/'
    owner: false
    group: false
  notify: restart he-caddy

- name: Copy caddy systemd service file
  ansible.builtin.template:
    src: 'he-caddy.service.j2'
    dest: '/etc/systemd/system/he-caddy.service'
    owner: root
    group: root
    mode: '0644'
  notify: restart he-caddy
