- name: Create upload-server directory
  ansible.builtin.file:
    path: '{{ happy_eyeballs.base_path }}/upload-server'
    owner: root
    group: root
    mode: '0755'
    state: 'directory'

- name: Copy upload-server files
  ansible.posix.synchronize:
    src: 'upload-server/'
    dest: '{{ happy_eyeballs.base_path }}/upload-server/'
    owner: false
    group: false
  notify: restart he-upload-server

- name: Copy upload-server docker compose file
  ansible.builtin.template:
    src: 'docker-compose.yml.j2'
    dest: '{{ happy_eyeballs.base_path }}/upload-server/docker-compose.yml'
    owner: root
    group: root
    mode: '0644'
  notify: restart he-upload-server

- name: Copy upload-server systemd service file
  ansible.builtin.template:
    src: 'he-upload-server.service.j2'
    dest: '/etc/systemd/system/he-upload-server.service'
    owner: root
    group: root
    mode: '0644'
  notify: restart he-upload-server

- name: Ensure upload-server result directories are present
  ansible.builtin.file:
    path: '{{ happy_eyeballs.base_path }}/{{ item }}'
    owner: '{{ happy_eyeballs.user.name }}'
    group: '{{ happy_eyeballs.user.name }}'
    mode: '0755'
    state: directory
  with_items:
    - '{{ happy_eyeballs.uploadserver.results_directory.v1 }}'
    - '{{ happy_eyeballs.uploadserver.results_directory.v1_rdns }}'
    - '{{ happy_eyeballs.uploadserver.results_directory.v2 }}'
    - '{{ happy_eyeballs.uploadserver.results_directory.v3_quic }}'
    - '{{ happy_eyeballs.uploadserver.results_directory.http3 }}'
  notify: restart he-upload-server
