---

- name: Import create certs
  tags:
    - createcerts
  ansible.builtin.import_tasks: create-certs.yml

- name: Setup nginx
  tags:
    - nginxsetup
  block:
    - name: Copy Tester site source directory
      ansible.posix.synchronize:
        src: site-src/
        dest: "{{ basepath }}/www-root/"
        owner: false
        group: false
        rsync_opts:
          - "--exclude=.DS_Store"

    - name: Ensure base directory is present
      ansible.builtin.file:
        path: "{{ server_base_path }}"
        owner: "{{ upload_user }}"
        group: "{{ upload_group }}"
        mode: '0755'
        state: 'directory'

    - name: Create venv if needed
      block:

        - name: Check if the file exists
          ansible.builtin.stat:
            path: "{{ server_venv_path }}"
          register: file_stat

        # - name: Debug file non-existence
        #   ansible.builtin.debug:
        #     msg: "The file does not exist."
        #   when: not file_stat.stat.exists

        - name: Create virtual environment
          when: not file_stat.stat.exists
          block:
            - name: Create Venv
              ansible.builtin.command: python3 -m venv {{ server_venv_path }}
              changed_when: true

            - name: Copy requirements
              ansible.builtin.copy:
                src: requirements.txt
                dest: "{{ server_base_path }}"
                owner: "{{ upload_user }}"
                group: "{{ upload_group }}"
                mode: '0644'

            - name: Install requirements
              ansible.builtin.pip:
                requirements: "{{ server_base_path }}/requirements.txt"
                virtualenv: "{{ server_venv_path }}"

            - name: Install uwsgi
              ansible.builtin.pip:
                name:
                  - uwsgi
                virtualenv: "{{ server_venv_path }}"

    - name: Copy Upload server python file
      ansible.builtin.template:
        src: results-upload.py
        dest: "{{ server_base_path }}/results-upload.py"
        owner: "{{ upload_user }}"
        group: "{{ upload_group }}"
        mode: '0644'
      register: upload_server

    - name: Ensure results directory is present
      ansible.builtin.file:
        path: "{{ upload_dir }}"
        owner: "{{ upload_user }}"
        group: "{{ upload_group }}"
        mode: '0755'
        state: 'directory'

    - name: Ensure results directory is present
      ansible.builtin.file:
        path: "{{ v2_upload_dir }}"
        owner: "{{ upload_user }}"
        group: "{{ upload_group }}"
        mode: '0755'
        state: 'directory'

    - name: Copy Upload server systemd service file
      ansible.builtin.template:
        src: he-upload-server.service.j2
        dest: /etc/systemd/system/he-upload-server.service
        owner: root
        group: root
        mode: '0644'
      register: upload_service

    # - name: Reload systemd and start Upload server
    #   ansible.builtin.systemd_service:
    #     name: he-upload-server.service
    #     daemon_reload: true
    #     state: restarted
    #   when: upload_service.changed or upload_server.changed

    - name: Copy Tester nginx config file
      ansible.builtin.template:
        src: happy-eyeballs-test.site.j2
        dest: /etc/nginx/sites-enabled/happy-eyeballs-test.site
        owner: root
        group: root
        mode: '0644'

    - name: Copy version only nginx config file
      ansible.builtin.template:
        src: happy-eyeballs-version-only.site.j2
        dest: /etc/nginx/sites-enabled/happy-eyeballs-version-only.site
        owner: root
        group: root
        mode: '0644'

    - name: Create delays.csv file
      ansible.builtin.template:
        src: delays.csv.j2
        dest: "{{ basepath }}/www-root/delays.csv"
        owner: root
        group: root
        mode: '0644'

    - name: Create he-test-domain file
      ansible.builtin.template:
        src: he-test-domain.j2
        dest: "{{ basepath }}/www-root/he-test-domain"
        owner: root
        group: root
        mode: '0644'

    - name: Copy Delay nginx config file
      ansible.builtin.template:
        src: happy-eyeballs-delay.site.j2
        dest: /etc/nginx/sites-enabled/happy-eyeballs-delay.site
        owner: root
        group: root
        mode: '0644'

    - name: Copy Delay v2 nginx config file
      ansible.builtin.template:
        src: happy-eyeballs-v2delay.site.j2
        dest: /etc/nginx/sites-enabled/happy-eyeballs-v2delay.site
        owner: root
        group: root
        mode: '0644'

    - name: Reload nginx service
      ansible.builtin.systemd_service:
        name: nginx.service
        state: 'reloaded'
