- name: Add nginx apt key
  ansible.builtin.apt_key:
    url: 'https://nginx.org/keys/nginx_signing.key'
    state: present

- name: Add nginx apt repository
  ansible.builtin.apt_repository:
    repo: 'deb https://nginx.org/packages/{{ os.name }} {{ os.version_codename }} nginx'
    state: present

- name: Install nginx
  ansible.builtin.apt:
    name: nginx
    update_cache: true
    state: latest
  notify: restart nginx

- name: Disable default nginx site
  ansible.builtin.file:
    path: '/etc/nginx/sites-enabled/default'
    state: absent
  notify: restart nginx
