- name: Add nginx apt key
  ansible.builtin.apt_key:
    url: 'https://nginx.org/keys/nginx_signing.key'
    state: present

- name: Add nginx apt repository
  ansible.builtin.apt_repository:
    repo: 'deb https://nginx.org/packages/{{ os.name }} {{ os.version_codename }} nginx'
    state: present

- name: Install nginx
  ansible.builtin.apt:
    name: nginx
    update_cache: true
    state: latest
  notify: restart nginx

- name: Disable default nginx site
  ansible.builtin.file:
    path: '/etc/nginx/sites-enabled/default'
    state: absent
  notify: restart nginx

- name: Create certificate for webtester domain
  block:
    - name: Check if certificate for webtester domain already exists
      ansible.builtin.stat:
        path: '/etc/letsencrypt/live/{{ happy_eyeballs.webtester.domains | first }}/cert.pem'
      register: webtester_certificate

    - name: Issue certificate for webtester domain
      ansible.builtin.command:
        cmd: >-
          certbot certonly
          --nginx
          --noninteractive
          --agree-tos
          --email {{ certbot.email }}
          -d {{ happy_eyeballs.webtester.domains | join(',') }}
      changed_when: true
      when: not webtester_certificate.stat.exists

- name: Copy nginx cors snippet
  ansible.builtin.template:
    src: 'nginx-config/snippets/cors.conf.j2'
    dest: '/etc/nginx/happy-eyeballs-cors.conf'
    owner: root
    group: root
    mode: '0644'

- name: Copy nginx config files
  ansible.builtin.template:
    src: 'nginx-config/{{ item }}.j2'
    dest: '/etc/nginx/conf.d/{{ item }}'
    owner: root
    group: root
    mode: '0644'
  with_items:
    - 'happy-eyeballs-test.conf'
    - 'happy-eyeballs-v1-delay.conf'
    - 'happy-eyeballs-v1-version-only.conf'
    - 'happy-eyeballs-v2-delay.conf'
    - 'happy-eyeballs-v3-quic.conf'
  notify: restart nginx
