- name: Copy webtester site source directory
  ansible.posix.synchronize:
    src: 'site-src/'
    dest: '{{ happy_eyeballs.base_path }}/www-root/'
    owner: false
    group: false
    rsync_opts:
      - '--exclude=.DS_Store'
  notify: restart nginx
  tags: [ 'nginx-webtester-src' ]

- name: Copy webtester static files
  ansible.builtin.template:
    src: 'static/{{ item }}.j2'
    dest: '{{ happy_eyeballs.base_path }}/www-root/{{ item }}'
    owner: root
    group: root
    mode: '0644'
  with_items:
    - 'delays.csv'
    - 'he-test-domain'
  notify: restart nginx

- name: Copy nginx cors snippet
  ansible.builtin.template:
    src: 'nginx-config/snippets/cors.conf.j2'
    dest: '/etc/nginx/happy-eyeballs-cors.conf'
    owner: root
    group: root
    mode: '0644'
  notify: restart nginx

- name: Copy nginx config files
  ansible.builtin.template:
    src: 'nginx-config/{{ item }}.j2'
    dest: '/etc/nginx/conf.d/{{ item }}'
    owner: root
    group: root
    mode: '0644'
  with_items:
    - 'happy-eyeballs-test.conf'
    - 'happy-eyeballs-v1-delay.conf'
    - 'happy-eyeballs-v1-version-only.conf'
    - 'happy-eyeballs-v2-delay.conf'
    - 'happy-eyeballs-v3-quic.conf'
  notify: restart nginx
