FROM caddy:2-builder-alpine AS builder

ADD custom-caddy-module /custom-caddy-module/

RUN xcaddy build \
    --with github.com/mholt/caddy-l4@master \
    --with happy-eyeballs-webtester-module=/custom-caddy-module

FROM caddy:latest

COPY --from=builder /usr/bin/caddy /usr/bin/caddy

RUN apk add --no-cache bash bind-tools
COPY caddy.json /etc/caddy

CMD ["caddy", "run", "--config", "/etc/caddy/Caddyfile"]
