webtester:
  hosts:
    # hostname for ssh to connect to
    host.example.com

  vars:
    happy_eyeballs:
      # dedicated user that will be created and used to run all required services
      user:
        uid: 2000
        name: 'happy-eyeballs'

      # all webtester-related files and results are stored inside this directory
      base_path: '/opt/happy-eyeballs'

      webtester:
        # domains pointing to the webtester frontend
        # (make sure to configure the A and AAAA records for this domain resolving to the IPv4 and IPv6 addresses configured below)
        domains:
          - 'he.example.com'
          - 'www.he.example.com'

        # network interface where the webtester addresses are assigned
        # (all configured addresses in this webtester section must be configurable on this interface - and will be added with ansible)
        interface: 'eth0'

        # dedicated IPv4 and IPv6 addresses with network masks (bits for CIDR notation) for the webtester frontend
        ipv4: '10.0.1.1'
        ipv4_net_mask: 24
        ipv6: '2001:db8::1:1'
        ipv6_net_mask: 112

      nameserver:
        # domain for the actual tests - the nameserver must be authoritative for all subdomains of this base domain
        base_domain: 'he-test.example.com'

        # prefix where all IPv6 addresses with delays are located in
        # (all other addresses such as the nameserver and ipv4/ipv6-version-only addresses must be outside prefix)
        ipv6_delay_prefix: '2001:db8::2:0/112'

        # network interface where the nameserver addresses are assigned
        # (all configured addresses in this nameserver section must be configurable on this interface - and will be added with ansible)
        interface: 'eth0'

        # nameserver's IPv4 and IPv6 addresses and network masks (bits for CIDR notation) - should be 2 IPv4 and 2 IPv6 addresses
        # (these addresses need to be added to DNS records inside the base domain, so that the nameserver can be resolved)
        ipv4:
          - '10.0.0.1'
          - '10.0.0.2'
        ipv4_net_mask: 24
        ipv6:
          - '2001:db8::1'
          - '2001:db8::2'
        ipv6_net_mask: 112

      webserver:
        # network interface where the webserver's addresses are assigned
        # (all configured addresses in this webserver section must be configurable on this interface - and will be added with ansible)
        interface: 'eth0'

        # network masks (bits for CIDR notation) of all addresses configured in this webserver section
        ipv4_net_mask: 24
        ipv6_net_mask: 112

        # addresses for all tests without delays
        ipv4: '10.0.1.2'
        ipv6: '2001:db8::1:2'

        # the webserver accepting HTTP/3 needs to bind on dedicated addresses
        http3:
          ipv4: '10.0.1.3'
          ipv6: '2001:db8::1:3'

        he_v3_quic:
          ipv4: '10.0.1.4'
          ipv6: '2001:db8::1:4'

        # any number of delays that will be used for the test cases
        # - each delay must have a distinct IPv4 and IPv6 address assigned
        # - delays are in milliseconds
        # - the flowid is used to apply the tc netem delay for the specific addresses; must be >= 0 and < 0xffff
        # - note: the last two delays are only used by the HEv2 test
        delays:
          - delay: 0
            flowid: 0
            ipv4: '10.0.2.100'
            ipv6: '2001:db8::2:100'

          - delay: 100
            flowid: 1
            ipv4: '10.0.2.101'
            ipv6: '2001:db8::2:101'

          - delay: 200
            flowid: 2
            ipv4: '10.0.2.102'
            ipv6: '2001:db8::2:102'

          - delay: 300
            flowid: 3
            ipv4: '10.0.2.103'
            ipv6: '2001:db8::2:103'

          - delay: 400
            flowid: 4
            ipv4: '10.0.2.104'
            ipv6: '2001:db8::2:104'

          - delay: 1000
            flowid: 5
            ipv4: '10.0.2.105'
            ipv6: '2001:db8::2:105'

          - delay: 10000
            flowid: 6
            ipv4: '10.0.2.106'
            ipv6: '2001:db8::2:106'

      result_upload:
        # the host and port that the result upload service is binding to
        # (can usually be left unchanged except the port is already in use)
        service:
          host: '127.0.0.1'
          port: 3000

      packet_capture:
        # the host and port that the packet capture service is binding to
        # (can usually be left unchanged except the port is already in use)
        service:
          host: '127.0.0.1'
          port: 3001

        tshark:
          pipe_path: '/tmp/tshark.pipe'

    os:
      # os name and version codename are required for installing the correct apt packages
      name: debian
      version_codename: bookworm

    certbot:
      # email required by Let's Encrypt for issuing the certificates
      email: 'admin@example.com'

    # systemd can be configured to send emails on service failures
    systemd_send_email_on_failure: false
